name: Android CI

on:
  push:
    paths:
      - 'apps/android/**'
      - '.github/workflows/ci-android.yml'
  pull_request:
    paths:
      - 'apps/android/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Debug (placeholder)
        run: |
          echo "Ainda não há projeto Gradle configurado. Este passo será ajustado quando importarmos o projeto Android."
          mkdir -p app/build/outputs/apk/debug
          echo "placeholder" > app/build/outputs/apk/debug/placeholder.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-placeholder
          path: apps/android/app/build/outputs/apk/debug/placeholder.txt